version: '3.8'

services:
  hazelcast-node1:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast-node1
    environment:
      - HZ_CLUSTERNAME=hazelcast-cluster
    networks:
      - hazelcast-network
    ports:
      - "5701:5701"

  hazelcast-node2:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast-node2
    environment:
      - HZ_CLUSTERNAME=hazelcast-cluster
    networks:
      - hazelcast-network

  hazelcast-mancenter:
    image: hazelcast/management-center:latest
    container_name: hazelcast-mancenter
    environment:
      - MC_DEFAULT_CLUSTER=hazelcast-cluster
      - MC_CLUSTER_MEMBER=hazelcast-node1:5701
    networks:
      - hazelcast-network
    ports:
      - "8080:8080"

networks:
  hazelcast-network:
    driver: bridge
