version: '3.8'

services:
  hazelcast-node1:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast-node1
    environment:
      - HZ_CLUSTERNAME=hazelcast-cluster
      - HZ_NETWORK_JOIN_TCPIP_ENABLED=true
      - HZ_NETWORK_JOIN_TCPIP_MEMBERS=hazelcast-node1,hazelcast-node2
      - HZ_NETWORK_PUBLICADDRESS=hazelcast-node1:5701
    networks:
      - hazelcast-network
    ports:
      - "5701:5701"

  hazelcast-node2:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast-node2
    environment:
      - HZ_CLUSTERNAME=hazelcast-cluster
      - HZ_NETWORK_JOIN_TCPIP_ENABLED=true
      - HZ_NETWORK_JOIN_TCPIP_MEMBERS=hazelcast-node1,hazelcast-node2
      - HZ_NETWORK_PUBLICADDRESS=hazelcast-node2:5701
    networks:
      - hazelcast-network
    ports:
      - "5702:5701"

  management-center:
    image: hazelcast/management-center:latest
    container_name: hazelcast-mancenter
    environment:
      - MC_DEFAULT_CLUSTER=hazelcast-cluster
      - MC_CLUSTER_MEMBER=hazelcast-node1:5701
    networks:
      - hazelcast-network
    ports:
      - "9090:8080"

networks:
  hazelcast-network:
    driver: bridge
