version: '3'
services:
  ignite-node-1:
    image: apacheignite/ignite:2.16.0  # Apache Ignite 2.16.0 sürümünü kullanıyoruz
    container_name: ignite-node-1
    ports:
      - "10800:10800"  # JDBC/ODBC bağlantısı için
      - "47100:47100"  # TCP bağlantı noktası
      - "47500:47500"  # Communication SPI için
      - "49112:49112"  # Discovery SPI için
    environment:
      - OPTION_LIBS=ignite-rest-http,ignite-indexing,control-center-agent
      - CONFIG_URI=/ignite-config.xml
      - IGNITE_WORK_DIR=/storage
      - JAVA_OPTS=-DIGNITE_PEER_CLASS_LOADING=true -DIGNITE_EVENT_DRIVEN_SERVICE_PROCESSOR_ENABLED=true
    volumes:
      - ignite-storage:/storage
      - ./ignite-config.xml:/ignite-config.xml  # Harici yapılandırma dosyanız
    networks:
      - ignite-cluster  # Hazelcast ile ortak ağ

volumes:
  ignite-storage:

networks:
  ignite-cluster:
    driver: bridge
