akka {
  actor {
    provider = "cluster"
  }

  remote {
    artery {
      transport = "tcp"
      canonical.hostname = "18.158.110.143"
      canonical.port = 2551
    }
  }

  cluster {
    seed-nodes = [
      "akka://myClusterSystem@18.158.110.143:2551"
    ]
    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
  }

  loggers = ["akka.event.slf4j.Slf4jLogger"]
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
  loglevel = "INFO"
}
